---
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: ansible-instance
    key_name: HYD
    vpc_subnet_id: subnet-0e70e5246ae5becd8
    instance_type: t3.micro
    security_group: my-sg
    region: ap-south-2
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    network:
      assign_public_ip: true
    image_id: ami-00727c10c4e1bec36
    tags:
      Environment: Testing

