---
- hosts: localhost
  connection: local

  tasks:
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "HYD"
      vpc_subnet_id: subnet-0e70e5246ae5becd8
      instance_type: t3.micro
      security_group: my-sg
      region: ap-south-2
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        environment: "{{ item.name }}"
    loop:
      - { image: "ami-00727c10c4e1bec36", name: "manage-node-1" } # Update AMI ID according 
      - { image: "ami-0e386fa0b67b8b12c", name: "manage-node-2" } # to your account
      - { image: "ami-0e386fa0b67b8b12c", name: "manage-node-3" }